'use strict';
const $=id=>document.getElementById(id);
const views=['setupView','loginView','remoteView'];
const actions=['next','previous','start','start-current','stop','black','white','first','last'];
const keys=['Arrow Left','Arrow Right','Page Up','Page Down','Space','Enter','Escape','Home','End','F1','F2','F3','F4','F5','F6','F7','F8','F9','F10','F11','F12','B','W','0','1','2','3','4','5','6','7','8','9'];
let token=sessionStorage.getItem('slidelink_token')||'';
let socket=null,requestId=1,profiles=[],activeProfile=null,lastPress=0;
let timerStarted=0,timerElapsed=0,timerRunning=false,timerInterval=0;

function show(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));}
function toast(message){const node=$('toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),1800);}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers});const body=await response.json().catch(()=>({error:{message:'Invalid device response'}}));if(!response.ok)throw new Error(body.error?.message||`HTTP ${response.status}`);return body;}
async function refreshSystem(){const state=await api('/api/v1/system',{headers:{}});$('deviceName').textContent=state.device;$('usbStatus').textContent=state.usb.ready?'USB ready':state.usb.mounted?'USB busy':'USB off';$('usbStatus').classList.toggle('offline',!state.usb.ready);if(state.setup_required){show('setupView');return false;}if(!token){show('loginView');return false;}return true;}

$('setupForm').addEventListener('submit',async event=>{event.preventDefault();try{await api('/api/v1/setup',{method:'POST',body:JSON.stringify({wifi_password:$('wifiPassword').value,pin:$('setupPin').value})});toast('Saved. Reconnect after restart.');event.submitter.disabled=true;}catch(error){toast(error.message);}});
$('loginForm').addEventListener('submit',async event=>{event.preventDefault();try{const data=await api('/api/v1/session',{method:'POST',body:JSON.stringify({pin:$('loginPin').value})});token=data.token;sessionStorage.setItem('slidelink_token',token);await enterRemote();}catch(error){toast(error.message);}});

async function enterRemote(){show('remoteView');try{await loadProfiles();connectSocket();await refreshSystem();}catch(error){if(/session|token|valid/i.test(error.message)){token='';sessionStorage.removeItem('slidelink_token');show('loginView');}toast(error.message);}}
async function loadProfiles(){const data=await api('/api/v1/profiles');profiles=data.profiles;activeProfile=profiles.find(p=>p.id===data.active_profile_id)||profiles[0];const select=$('profileSelect');select.innerHTML=profiles.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('');select.value=String(activeProfile.id);}
function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}

function connectSocket(){if(socket)socket.close();const scheme=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${location.host}/ws`);socket.onopen=()=>setWs(true);socket.onclose=()=>{setWs(false);setTimeout(()=>token&&connectSocket(),1500);};socket.onerror=()=>socket.close();socket.onmessage=event=>handleMessage(JSON.parse(event.data));}
function setWs(online){$('wsStatus').textContent=online?'Connected':'Offline';$('wsStatus').classList.toggle('offline',!online);}
function handleMessage(message){if(message.type==='command_accepted')$('resultLine').textContent=`Queued #${message.command_id}`;if(message.type==='command_result'){const ok=message.status==='executed';$('resultLine').textContent=ok?`Executed #${message.command_id} · ${message.duration_ms} ms`:`${message.status}: ${message.error?.message||'failed'}`;toast(ok?'Command executed':message.error?.message||'Command failed');}setTimeout(refreshSystem,80);}
function sendCommand(action,slide){const now=performance.now();if(now-lastPress<125)return;lastPress=now;if(!socket||socket.readyState!==WebSocket.OPEN){toast('WebSocket is offline');return;}socket.send(JSON.stringify({type:'execute_command',token,request_id:requestId++,action,...(slide?{slide}:{}),}));}
document.querySelectorAll('.command').forEach(button=>{button.addEventListener('pointerdown',()=>button.classList.add('pressed'));button.addEventListener('pointerup',()=>button.classList.remove('pressed'));button.addEventListener('pointercancel',()=>button.classList.remove('pressed'));button.addEventListener('click',()=>sendCommand(button.dataset.action));});
$('gotoForm').addEventListener('submit',event=>{event.preventDefault();sendCommand('goto',Number($('slideNumber').value));});
$('profileSelect').addEventListener('change',async event=>{try{const id=Number(event.target.value);const saved=await api(`/api/v1/profiles/${id}/activate`,{method:'POST',body:'{}'});activeProfile=saved;await loadProfiles();toast(`${saved.name} active`);}catch(error){toast(error.message);event.target.value=String(activeProfile.id);}});

function timerText(milliseconds){const seconds=Math.floor(milliseconds/1000);return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function renderTimer(){const current=timerElapsed+(timerRunning?Date.now()-timerStarted:0);$('timerOutput').textContent=timerText(current);}
$('timerToggle').addEventListener('click',()=>{if(timerRunning){timerElapsed+=Date.now()-timerStarted;timerRunning=false;$('timerToggle').textContent='Start';clearInterval(timerInterval);}else{timerStarted=Date.now();timerRunning=true;$('timerToggle').textContent='Pause';timerInterval=setInterval(renderTimer,250);}renderTimer();});
$('timerReset').addEventListener('click',()=>{timerElapsed=0;timerStarted=Date.now();renderTimer();});

$('settingsButton').addEventListener('click',()=>{activeProfile=profiles.find(p=>p.id===Number($('profileSelect').value));$('profileName').value=activeProfile.name;renderEditor(activeProfile);$('editPin').value='';$('profileDialog').showModal();});
function renderEditor(profile){const editor=$('bindingEditor');editor.innerHTML='';actions.forEach(action=>{const binding=profile.bindings[action];const section=document.createElement('section');section.className='binding';section.dataset.action=action;section.innerHTML=`<div class="binding-title"><h3>${action}</h3><div><button class="test-binding" type="button">Test</button> <label><input class="enabled" type="checkbox" ${binding.enabled?'checked':''}> Enabled</label></div></div><div class="steps"></div><button class="add-step" type="button">+ Add step</button>`;editor.appendChild(section);binding.steps.forEach(step=>addStep(section,step));section.querySelector('.add-step').onclick=()=>{if(section.querySelectorAll('.step').length<4)addStep(section,{key:'Arrow Right',modifiers:[],delay_after_ms:0});};section.querySelector('.test-binding').onclick=()=>testBinding(section);});}
function addStep(section,step){const row=document.createElement('div');row.className='step';row.innerHTML=`<select class="key">${keys.map(key=>`<option ${key===step.key?'selected':''}>${key}</option>`).join('')}</select><input class="delay" type="number" min="0" max="1000" value="${step.delay_after_ms}" aria-label="Delay milliseconds"><div class="mods">${['Shift','Ctrl','Alt'].map(mod=>`<label><input type="checkbox" data-mod="${mod}" ${step.modifiers.includes(mod)?'checked':''}>${mod}</label>`).join('')}<button class="remove" type="button">×</button></div>`;row.querySelector('.remove').onclick=()=>row.remove();section.querySelector('.steps').appendChild(row);}
function editorProfile(){const output={name:$('profileName').value.trim(),bindings:{},goto:{enabled:activeProfile.goto.enabled,submit_key:activeProfile.goto.submit_key,digit_delay_ms:activeProfile.goto.digit_delay_ms}};document.querySelectorAll('#bindingEditor .binding').forEach(section=>{const steps=[...section.querySelectorAll('.step')].map(row=>({key:row.querySelector('.key').value,modifiers:[...row.querySelectorAll('[data-mod]:checked')].map(input=>input.dataset.mod),delay_after_ms:Number(row.querySelector('.delay').value)}));output.bindings[section.dataset.action]={enabled:section.querySelector('.enabled').checked,steps};});return output;}
async function testBinding(section){try{const binding=editorProfile().bindings[section.dataset.action];await api(`/api/v1/profiles/${activeProfile.id}/test`,{method:'POST',headers:{'X-SlideLink-PIN':$('editPin').value},body:JSON.stringify({action:section.dataset.action,binding})});toast('Temporary binding executed');}catch(error){toast(error.message);}}
$('saveProfile').addEventListener('click',async()=>{try{const pin=$('editPin').value;const saved=await api(`/api/v1/profiles/${activeProfile.id}`,{method:'PUT',headers:{'X-SlideLink-PIN':pin},body:JSON.stringify(editorProfile())});$('profileDialog').close();await loadProfiles();toast(`Saved revision ${saved.revision}`);}catch(error){toast(error.message);}});
$('resetProfile').addEventListener('click',async()=>{try{const saved=await api(`/api/v1/profiles/${activeProfile.id}/reset`,{method:'POST',headers:{'X-SlideLink-PIN':$('editPin').value},body:'{}'});activeProfile=saved;renderEditor(saved);$('profileName').value=saved.name;await loadProfiles();toast('Factory profile restored');}catch(error){toast(error.message);}});

(async()=>{try{if(await refreshSystem())await enterRemote();}catch(error){toast(error.message);show('loginView');}})();
