'use strict';

const $=id=>document.getElementById(id);
const views=['setupView','loginView','remoteView'];
const actions=['next','previous','start','start-current','stop','black','white','first','last'];
const keys=['Arrow Left','Arrow Right','Page Up','Page Down','Space','Enter','Escape','Home','End','F1','F2','F3','F4','F5','F6','F7','F8','F9','F10','F11','F12','B','W','0','1','2','3','4','5','6','7','8','9'];
const messages={
  en:{
    'common.pin':'Control PIN','common.yes':'Yes','common.no':'No','common.enabled':'Enabled',
    'setup.eyebrow':'FIRST-RUN SETUP','setup.title':'Secure your SlideLink','setup.description':'Choose a private Wi-Fi password and a 4-8 digit control PIN. The device restarts once.','setup.wifi':'New Wi-Fi password','setup.save':'Save and restart','setup.saved':'Saved. Reconnect after the restart.',
    'login.eyebrow':'LOCAL PRESENTER','login.description':'Enter the control PIN. Communication stays on the direct USB or local Wi-Fi link.','login.connect':'Connect',
    'remote.profile':'Active profile','remote.slide':'Slide','remote.go':'GO','remote.timer':'TIMER','remote.start':'Start','remote.pause':'Pause','remote.reset':'Reset','remote.ready':'Ready','remote.feedbackNote':'Slide numbers are keyboard commands; presentation software does not report the current slide back.','remote.connected':'Connected','remote.offline':'Offline','remote.usbReady':'USB ready','remote.usbBusy':'USB busy','remote.usbOff':'USB off','remote.queued':'Queued #{id}','remote.executed':'Executed #{id} · {ms} ms','remote.commandOk':'Command executed','remote.socketOff':'Control connection is offline',
    'action.next':'NEXT','action.previous':'PREVIOUS','action.start':'Start','action.start-current':'Current','action.stop':'End','action.black':'Black','action.white':'White','action.first':'First','action.last':'Last',
    'profile.edit':'Edit profile','profile.eyebrow':'LIVE PROFILE','profile.title':'Edit controls','profile.name':'Profile name','profile.confirmPin':'Confirm current PIN','profile.restore':'Restore profile','profile.save':'Save profile','profile.test':'Test','profile.addStep':'+ Add step','profile.delay':'Delay, ms','profile.testOk':'Temporary binding executed','profile.saved':'Saved revision {revision}','profile.restored':'Factory profile restored','profile.active':'{name} active',
    'settings.title':'Device settings','settings.device':'Device information','settings.access':'Local access','settings.accessHelp':'USB is preferred. The IP address remains available when mDNS is not resolved. The USB link provides no gateway or DNS.','settings.security':'Credentials','settings.currentPin':'Current PIN','settings.newWifi':'New Wi-Fi password (optional)','settings.newPin':'New PIN (optional)','settings.save':'Save and restart','settings.saved':'Credentials saved. The device is restarting.','settings.firmwareUpdate':'Firmware update','settings.firmwareHelp':'Choose an official SlideLink .bin image. The device validates it, writes the inactive slot and rolls back if startup fails.','settings.install':'Validate and install','settings.updating':'Uploading firmware…','settings.updateDone':'Firmware {version} installed. Restarting…','settings.factory':'Factory reset','settings.factoryHelp':'Deletes the PIN, Wi-Fi password and custom profiles. A new unique setup credential is generated.','settings.factoryButton':'Erase all settings','settings.factoryConfirm':'Erase all SlideLink settings and profiles? This cannot be undone.','settings.factoryDone':'Factory reset complete. The device is restarting.','settings.chooseChange':'Enter a new Wi-Fi password, a new PIN, or both.','settings.deviceName':'Device','settings.firmware':'Firmware','settings.hid':'USB HID','settings.ncm':'USB network','settings.ncmIp':'USB address','settings.wifi':'Wi-Fi clients','settings.secureBoot':'Secure Boot','settings.encryption':'Flash encryption','settings.on':'On','settings.off':'Off','settings.linkUp':'Connected','settings.linkDown':'Disconnected',
    'error.unauthorized':'The session expired. Enter the PIN again.','error.invalid_pin':'The PIN is incorrect.','error.login_throttled':'Too many attempts. Wait 30 seconds.','error.invalid_setup':'Use a Wi-Fi password of 8-63 characters and a PIN of 4-8 digits.','error.invalid_settings':'Check the Wi-Fi password and PIN format.','error.usb_not_mounted':'Connect the native USB port and wait for USB ready.','error.queue_full':'Too many commands. Try again.','error.router_busy':'The presenter is busy. Try again.','error.action_disabled':'This action is disabled in the active profile.','error.invalid_firmware':'The firmware is corrupt or intended for another product.','error.update_unavailable':'The update does not fit or another update is active.','error.network':'SlideLink did not respond. Check the USB or Wi-Fi link.','error.deviceResponse':'Invalid response from the device.','error.failed':'Operation failed.'
  },
  ru:{
    'common.pin':'PIN управления','common.yes':'Да','common.no':'Нет','common.enabled':'Включено',
    'setup.eyebrow':'ПЕРВАЯ НАСТРОЙКА','setup.title':'Защитите SlideLink','setup.description':'Задайте личный пароль Wi-Fi и PIN управления из 4-8 цифр. Устройство перезагрузится один раз.','setup.wifi':'Новый пароль Wi-Fi','setup.save':'Сохранить и перезапустить','setup.saved':'Сохранено. Подключитесь снова после перезапуска.',
    'login.eyebrow':'ЛОКАЛЬНЫЙ ПРЕЗЕНТЕР','login.description':'Введите PIN управления. Обмен данными идёт только по прямому USB- или локальному Wi-Fi-соединению.','login.connect':'Подключиться',
    'remote.profile':'Активный профиль','remote.slide':'Слайд','remote.go':'ПЕРЕЙТИ','remote.timer':'ТАЙМЕР','remote.start':'Старт','remote.pause':'Пауза','remote.reset':'Сброс','remote.ready':'Готово','remote.feedbackNote':'Номер слайда передаётся как клавиатурная команда; программа презентации не сообщает текущий слайд обратно.','remote.connected':'Подключено','remote.offline':'Нет связи','remote.usbReady':'USB готов','remote.usbBusy':'USB занят','remote.usbOff':'USB отключён','remote.queued':'В очереди #{id}','remote.executed':'Выполнено #{id} · {ms} мс','remote.commandOk':'Команда выполнена','remote.socketOff':'Нет соединения с управлением',
    'action.next':'СЛЕДУЮЩИЙ','action.previous':'ПРЕДЫДУЩИЙ','action.start':'С начала','action.start-current':'С текущего','action.stop':'Завершить','action.black':'Чёрный экран','action.white':'Белый экран','action.first':'Первый','action.last':'Последний',
    'profile.edit':'Редактировать профиль','profile.eyebrow':'АКТИВНЫЙ ПРОФИЛЬ','profile.title':'Настройка управления','profile.name':'Название профиля','profile.confirmPin':'Подтвердите текущий PIN','profile.restore':'Сбросить профиль','profile.save':'Сохранить профиль','profile.test':'Проверить','profile.addStep':'+ Добавить шаг','profile.delay':'Задержка, мс','profile.testOk':'Временная команда выполнена','profile.saved':'Сохранена ревизия {revision}','profile.restored':'Заводской профиль восстановлен','profile.active':'Профиль «{name}» активен',
    'settings.title':'Настройки устройства','settings.device':'Информация об устройстве','settings.access':'Локальный доступ','settings.accessHelp':'Предпочтителен USB. IP-адрес работает, даже если mDNS-имя недоступно. USB-интерфейс не выдаёт шлюз и DNS.','settings.security':'Данные доступа','settings.currentPin':'Текущий PIN','settings.newWifi':'Новый пароль Wi-Fi (необязательно)','settings.newPin':'Новый PIN (необязательно)','settings.save':'Сохранить и перезапустить','settings.saved':'Данные сохранены. Устройство перезапускается.','settings.firmwareUpdate':'Обновление прошивки','settings.firmwareHelp':'Выберите официальный .bin-файл SlideLink. Устройство проверит его, запишет в неактивный слот и откатится при неудачном запуске.','settings.install':'Проверить и установить','settings.updating':'Загрузка прошивки…','settings.updateDone':'Прошивка {version} установлена. Перезапуск…','settings.factory':'Заводской сброс','settings.factoryHelp':'Удаляет PIN, пароль Wi-Fi и изменённые профили. Будет создан новый уникальный setup credential.','settings.factoryButton':'Удалить все настройки','settings.factoryConfirm':'Удалить все настройки и профили SlideLink? Отменить это действие нельзя.','settings.factoryDone':'Заводской сброс выполнен. Устройство перезапускается.','settings.chooseChange':'Введите новый пароль Wi-Fi, новый PIN или оба значения.','settings.deviceName':'Устройство','settings.firmware':'Прошивка','settings.hid':'USB HID','settings.ncm':'USB-сеть','settings.ncmIp':'USB-адрес','settings.wifi':'Клиенты Wi-Fi','settings.secureBoot':'Secure Boot','settings.encryption':'Шифрование Flash','settings.on':'Включено','settings.off':'Выключено','settings.linkUp':'Подключена','settings.linkDown':'Отключена',
    'error.unauthorized':'Сессия истекла. Введите PIN снова.','error.invalid_pin':'Неверный PIN.','error.login_throttled':'Слишком много попыток. Подождите 30 секунд.','error.invalid_setup':'Пароль Wi-Fi должен содержать 8-63 символа, PIN — 4-8 цифр.','error.invalid_settings':'Проверьте формат пароля Wi-Fi и PIN.','error.usb_not_mounted':'Подключите native USB и дождитесь готовности USB.','error.queue_full':'Слишком много команд. Повторите позже.','error.router_busy':'Презентер занят. Повторите позже.','error.action_disabled':'Действие отключено в активном профиле.','error.invalid_firmware':'Прошивка повреждена или предназначена для другого продукта.','error.update_unavailable':'Образ не помещается или уже идёт обновление.','error.network':'SlideLink не отвечает. Проверьте USB- или Wi-Fi-соединение.','error.deviceResponse':'Некорректный ответ устройства.','error.failed':'Не удалось выполнить операцию.'
  }
};

let language=localStorage.getItem('slidelink_language')||((navigator.language||'en').toLowerCase().startsWith('ru')?'ru':'en');
let token=sessionStorage.getItem('slidelink_token')||'';
let socket=null,reconnectTimer=0,requestId=1,profiles=[],activeProfile=null,lastPress=0,lastState=null;
let timerStarted=0,timerElapsed=0,timerRunning=false,timerInterval=0,toastTimer=0;

function tr(key,values={}){let value=messages[language][key]??messages.en[key]??key;Object.entries(values).forEach(([name,replacement])=>{value=value.replaceAll(`{${name}}`,String(replacement));});return value;}
function errorText(code,fallback){const key=`error.${code||'failed'}`;const translated=tr(key);return translated===key?(fallback||tr('error.failed')):translated;}
function applyLanguage(){document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=tr(node.dataset.i18n));document.querySelectorAll('[data-i18n-title]').forEach(node=>node.title=tr(node.dataset.i18nTitle));document.querySelectorAll('[data-i18n-aria]').forEach(node=>node.setAttribute('aria-label',tr(node.dataset.i18nAria)));document.querySelectorAll('[data-lang]').forEach(node=>node.classList.toggle('active',node.dataset.lang===language));renderConnection();renderTimerButton();if($('profileDialog').open&&activeProfile)renderEditor(activeProfile);if(lastState)renderDeviceDetails(lastState);}
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{language=button.dataset.lang;localStorage.setItem('slidelink_language',language);applyLanguage();}));
function show(id){views.forEach(view=>$(view).classList.toggle('hidden',view!==id));}
function toast(message){clearTimeout(toastTimer);const node=$('toast');node.textContent=message;node.classList.add('show');toastTimer=setTimeout(()=>node.classList.remove('show'),2400);}
function logout(){token='';sessionStorage.removeItem('slidelink_token');clearTimeout(reconnectTimer);if(socket)socket.close();show('loginView');}
async function api(path,options={}){const headers={...(options.headers||{})};if(options.body!==undefined&&!headers['Content-Type'])headers['Content-Type']='application/json';if(token)headers.Authorization=`Bearer ${token}`;let response;try{response=await fetch(path,{...options,headers,cache:'no-store'});}catch(_){throw new Error(tr('error.network'));}const text=await response.text();let body={};if(text){try{body=JSON.parse(text);}catch(_){throw new Error(tr('error.deviceResponse'));}}if(!response.ok){const code=body.error?.code||'failed';const error=new Error(errorText(code,body.error?.message));error.code=code;if(code==='unauthorized')logout();throw error;}return body;}

function renderConnection(){const online=socket?.readyState===WebSocket.OPEN;$('wsStatus').textContent=tr(online?'remote.connected':'remote.offline');$('wsStatus').classList.toggle('offline',!online);if(lastState){$('usbStatus').textContent=tr(lastState.usb.ready?'remote.usbReady':lastState.usb.mounted?'remote.usbBusy':'remote.usbOff');$('usbStatus').classList.toggle('offline',!lastState.usb.ready);}}
async function refreshSystem(){const state=await api('/api/v1/system');lastState=state;$('deviceName').textContent=state.device;renderConnection();if(state.setup_required){show('setupView');return false;}if(!token){show('loginView');return false;}if($('settingsDialog').open)renderDeviceDetails(state);return true;}

$('setupForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{await api('/api/v1/setup',{method:'POST',body:JSON.stringify({wifi_password:$('wifiPassword').value,pin:$('setupPin').value})});toast(tr('setup.saved'));}catch(error){button.disabled=false;toast(error.message);}});
$('loginForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const data=await api('/api/v1/session',{method:'POST',body:JSON.stringify({pin:$('loginPin').value})});token=data.token;sessionStorage.setItem('slidelink_token',token);$('loginPin').value='';await enterRemote();}catch(error){toast(error.message);}finally{button.disabled=false;}});

async function enterRemote(){show('remoteView');try{await loadProfiles();connectSocket();await refreshSystem();}catch(error){toast(error.message);}}
async function loadProfiles(){const data=await api('/api/v1/profiles');profiles=data.profiles;activeProfile=profiles.find(profile=>profile.id===data.active_profile_id)||profiles[0];const select=$('profileSelect');select.replaceChildren(...profiles.map(profile=>{const option=document.createElement('option');option.value=profile.id;option.textContent=profile.name;return option;}));select.value=String(activeProfile.id);}
function connectSocket(){clearTimeout(reconnectTimer);if(socket){socket.onclose=null;socket.close();}const scheme=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${location.host}/ws`);socket.onopen=renderConnection;socket.onclose=()=>{renderConnection();reconnectTimer=setTimeout(()=>token&&connectSocket(),1500);};socket.onerror=()=>socket.close();socket.onmessage=event=>{try{handleMessage(JSON.parse(event.data));}catch(_){toast(tr('error.deviceResponse'));}};}
function handleMessage(message){if(message.type==='command_accepted')$('resultLine').textContent=tr('remote.queued',{id:message.command_id});if(message.type==='command_result'){const ok=message.status==='executed';const failure=errorText(message.error?.code,message.error?.message||message.status);$('resultLine').textContent=ok?tr('remote.executed',{id:message.command_id,ms:message.duration_ms}):failure;toast(ok?tr('remote.commandOk'):failure);}setTimeout(()=>refreshSystem().catch(()=>{}),80);}
function sendCommand(action,slide){const now=performance.now();if(now-lastPress<125)return;lastPress=now;if(!socket||socket.readyState!==WebSocket.OPEN){toast(tr('remote.socketOff'));return;}socket.send(JSON.stringify({type:'execute_command',token,request_id:requestId++,action,...(slide?{slide}:{})}));}
document.querySelectorAll('.command').forEach(button=>{button.addEventListener('pointerdown',()=>button.classList.add('pressed'));['pointerup','pointercancel','pointerleave'].forEach(name=>button.addEventListener(name,()=>button.classList.remove('pressed')));button.addEventListener('click',()=>sendCommand(button.dataset.action));});
$('gotoForm').addEventListener('submit',event=>{event.preventDefault();sendCommand('goto',Number($('slideNumber').value));});
$('profileSelect').addEventListener('change',async event=>{try{const saved=await api(`/api/v1/profiles/${Number(event.target.value)}/activate`,{method:'POST',body:'{}'});activeProfile=saved;await loadProfiles();toast(tr('profile.active',{name:saved.name}));}catch(error){toast(error.message);event.target.value=String(activeProfile.id);}});

function timerText(milliseconds){const seconds=Math.floor(milliseconds/1000);return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function renderTimer(){const current=timerElapsed+(timerRunning?Date.now()-timerStarted:0);$('timerOutput').textContent=timerText(current);}
function renderTimerButton(){$('timerToggle').textContent=tr(timerRunning?'remote.pause':'remote.start');}
$('timerToggle').addEventListener('click',()=>{if(timerRunning){timerElapsed+=Date.now()-timerStarted;timerRunning=false;clearInterval(timerInterval);}else{timerStarted=Date.now();timerRunning=true;timerInterval=setInterval(renderTimer,250);}renderTimerButton();renderTimer();});
$('timerReset').addEventListener('click',()=>{timerElapsed=0;timerStarted=Date.now();renderTimer();});

$('editProfileButton').addEventListener('click',()=>{activeProfile=profiles.find(profile=>profile.id===Number($('profileSelect').value));$('profileName').value=activeProfile.name;renderEditor(activeProfile);$('editPin').value='';$('profileDialog').showModal();});
function renderEditor(profile){const editor=$('bindingEditor');editor.replaceChildren();actions.forEach(action=>{const binding=profile.bindings[action];const section=document.createElement('section');section.className='binding';section.dataset.action=action;const title=document.createElement('div');title.className='binding-title';const heading=document.createElement('h3');heading.textContent=tr(`action.${action}`);const tools=document.createElement('div');tools.className='binding-tools';const test=document.createElement('button');test.type='button';test.className='test-binding';test.textContent=tr('profile.test');const enabled=document.createElement('label');enabled.innerHTML=`<input class="enabled" type="checkbox" ${binding.enabled?'checked':''}> ${tr('common.enabled')}`;tools.append(test,enabled);title.append(heading,tools);const steps=document.createElement('div');steps.className='steps';const add=document.createElement('button');add.type='button';add.className='add-step';add.textContent=tr('profile.addStep');section.append(title,steps,add);editor.appendChild(section);binding.steps.forEach(step=>addStep(section,step));add.onclick=()=>{if(section.querySelectorAll('.step').length<4)addStep(section,{key:'Arrow Right',modifiers:[],delay_after_ms:0});};test.onclick=()=>testBinding(section);});}
function addStep(section,step){const row=document.createElement('div');row.className='step';const select=document.createElement('select');keys.forEach(key=>{const option=document.createElement('option');option.value=key;option.textContent=key;option.selected=key===step.key;select.appendChild(option);});select.className='key';const delay=document.createElement('input');delay.className='delay';delay.type='number';delay.min='0';delay.max='1000';delay.value=step.delay_after_ms;delay.setAttribute('aria-label',tr('profile.delay'));const mods=document.createElement('div');mods.className='mods';['Shift','Ctrl','Alt'].forEach(mod=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.dataset.mod=mod;input.checked=step.modifiers.includes(mod);label.append(input,mod);mods.appendChild(label);});const remove=document.createElement('button');remove.type='button';remove.className='remove';remove.textContent='×';remove.onclick=()=>row.remove();mods.appendChild(remove);row.append(select,delay,mods);section.querySelector('.steps').appendChild(row);}
function editorProfile(){const output={name:$('profileName').value.trim(),bindings:{},goto:{enabled:activeProfile.goto.enabled,submit_key:activeProfile.goto.submit_key,digit_delay_ms:activeProfile.goto.digit_delay_ms}};document.querySelectorAll('#bindingEditor .binding').forEach(section=>{const steps=[...section.querySelectorAll('.step')].map(row=>({key:row.querySelector('.key').value,modifiers:[...row.querySelectorAll('[data-mod]:checked')].map(input=>input.dataset.mod),delay_after_ms:Number(row.querySelector('.delay').value)}));output.bindings[section.dataset.action]={enabled:section.querySelector('.enabled').checked,steps};});return output;}
async function testBinding(section){try{const binding=editorProfile().bindings[section.dataset.action];await api(`/api/v1/profiles/${activeProfile.id}/test`,{method:'POST',headers:{'X-SlideLink-PIN':$('editPin').value},body:JSON.stringify({action:section.dataset.action,binding})});toast(tr('profile.testOk'));}catch(error){toast(error.message);}}
$('saveProfile').addEventListener('click',async()=>{try{const saved=await api(`/api/v1/profiles/${activeProfile.id}`,{method:'PUT',headers:{'X-SlideLink-PIN':$('editPin').value},body:JSON.stringify(editorProfile())});$('profileDialog').close();await loadProfiles();toast(tr('profile.saved',{revision:saved.revision}));}catch(error){toast(error.message);}});
$('resetProfile').addEventListener('click',async()=>{try{const saved=await api(`/api/v1/profiles/${activeProfile.id}/reset`,{method:'POST',headers:{'X-SlideLink-PIN':$('editPin').value},body:'{}'});activeProfile=saved;renderEditor(saved);$('profileName').value=saved.name;await loadProfiles();toast(tr('profile.restored'));}catch(error){toast(error.message);}});

function detail(label,value){const term=document.createElement('dt');term.textContent=label;const description=document.createElement('dd');description.textContent=value;return [term,description];}
function renderDeviceDetails(state){const details=$('deviceDetails');const net=state.usb.network||{};details.replaceChildren(...detail(tr('settings.deviceName'),state.device),...detail(tr('settings.firmware'),state.firmware),...detail(tr('settings.hid'),state.usb.ready?tr('settings.linkUp'):tr('settings.linkDown')),...detail(tr('settings.ncm'),net.link_up?tr('settings.linkUp'):tr('settings.linkDown')),...detail(tr('settings.ncmIp'),net.ip||'192.168.55.1'),...detail(tr('settings.wifi'),String(state.wifi.clients)),...detail(tr('settings.secureBoot'),tr(state.security?.secure_boot?'settings.on':'settings.off')),...detail(tr('settings.encryption'),tr(state.security?.flash_encryption?'settings.on':'settings.off')));}
$('settingsButton').addEventListener('click',async()=>{try{await refreshSystem();renderDeviceDetails(lastState);$('currentPin').value='';$('newWifiPassword').value='';$('newPin').value='';$('factoryPin').value='';$('settingsDialog').showModal();}catch(error){toast(error.message);}});
$('credentialsForm').addEventListener('submit',async event=>{event.preventDefault();const wifi=$('newWifiPassword').value;const pin=$('newPin').value;if(!wifi&&!pin){toast(tr('settings.chooseChange'));return;}const body={current_pin:$('currentPin').value,...(wifi?{wifi_password:wifi}:{}),...(pin?{new_pin:pin}:{})};const button=event.submitter;button.disabled=true;try{await api('/api/v1/settings',{method:'PUT',body:JSON.stringify(body)});sessionStorage.removeItem('slidelink_token');toast(tr('settings.saved'));}catch(error){button.disabled=false;toast(error.message);}});
$('firmwareForm').addEventListener('submit',async event=>{event.preventDefault();const file=$('firmwareFile').files[0];if(!file)return;const button=event.submitter;const progress=$('firmwareProgress');button.disabled=true;progress.classList.remove('hidden');progress.removeAttribute('value');toast(tr('settings.updating'));try{const result=await api('/api/v1/firmware',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});progress.value=100;toast(tr('settings.updateDone',{version:result.version}));}catch(error){progress.classList.add('hidden');button.disabled=false;toast(error.message);}});
$('factoryForm').addEventListener('submit',async event=>{event.preventDefault();if(!confirm(tr('settings.factoryConfirm')))return;const button=event.submitter;button.disabled=true;try{await api('/api/v1/factory-reset',{method:'POST',body:JSON.stringify({pin:$('factoryPin').value})});sessionStorage.removeItem('slidelink_token');toast(tr('settings.factoryDone'));}catch(error){button.disabled=false;toast(error.message);}});

document.addEventListener('visibilitychange',()=>{if(!document.hidden&&token&&(!socket||socket.readyState>1))connectSocket();});
applyLanguage();$('resultLine').textContent=tr('remote.ready');setInterval(()=>refreshSystem().catch(()=>{}),3000);
(async()=>{try{if(await refreshSystem())await enterRemote();}catch(error){toast(error.message);show('loginView');}})();
