/* USB HID Usage IDs used by the presenter mapping tests. */
#pragma once

#define KEYBOARD_MODIFIER_LEFTSHIFT 0x02
#define KEYBOARD_MODIFIER_LEFTALT   0x04
#define KEYBOARD_MODIFIER_LEFTCTRL  0x01
#define HID_KEY_1                   0x1E
#define HID_KEY_2                   0x1F
#define HID_KEY_3                   0x20
#define HID_KEY_4                   0x21
#define HID_KEY_5                   0x22
#define HID_KEY_6                   0x23
#define HID_KEY_7                   0x24
#define HID_KEY_8                   0x25
#define HID_KEY_9                   0x26
#define HID_KEY_0                   0x27
#define HID_KEY_SPACE               0x2C
#define HID_KEY_F1                  0x3A
#define HID_KEY_F2                  0x3B
#define HID_KEY_F3                  0x3C
#define HID_KEY_F4                  0x3D
#define HID_KEY_B                   0x05
#define HID_KEY_W                   0x1A
#define HID_KEY_ENTER               0x28
#define HID_KEY_ESCAPE              0x29
#define HID_KEY_F5                  0x3E
#define HID_KEY_F6                  0x3F
#define HID_KEY_F7                  0x40
#define HID_KEY_F8                  0x41
#define HID_KEY_F9                  0x42
#define HID_KEY_F10                 0x43
#define HID_KEY_F11                 0x44
#define HID_KEY_F12                 0x45
#define HID_KEY_HOME                0x4A
#define HID_KEY_PAGE_UP             0x4B
#define HID_KEY_END                 0x4D
#define HID_KEY_PAGE_DOWN           0x4E
#define HID_KEY_ARROW_RIGHT         0x4F
#define HID_KEY_ARROW_LEFT          0x50
